# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda install conda-build anaconda-client pytest pytest-cov
  - conda config --set auto_update_conda no
  - conda build conda.recipe --no-test
  - conda install --use-local lazyprofiler
  - conda info -a
script:
  - pytest -v --color=yes --cov=lazyprofiler tests
after_success:
  - conda install -c conda-forge codecov
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: __token__
  password:
    secure: lDbbKlxoBx1Q2FHlTAETm1J/p3UDzTXkWlkStmJ4f4+URVpg+mIYS24qIljTkPY01ViRA4gt9XRS8D4l4OjAP6hpJZNGhUCAEvnVJk7g2xSCiRWLwy+UjuSjCCE9P1ZeYBxJ1qNA1RsBFso6fSSP0taMyPnGMxBIUUKTCfnicqbJYoMJulxhYDzWFzKtMSEhrmpStPEJ0YHufbmmhIxbMiQ8HRAL6RefoVx4rTMk+n+wseHRr69iIvvFRyK6ocwndiXbu/uiiGyQoEw0y3KwIBv55O+VSJzI+DHoDefDjUv4ol/CZ02LQEZAhpWLDHYBrCNFWmvii3wtxDO1h4Lpe4QAUptJxT/6jGDn0+gN2rD1yCvP9g/w/Xy/aFU/McLqi/vNXU/8UOtQ+qSSm5PMCdaasRu6rk0//6bo9Fir4v7Ww5AycWznDagR6pcyrRNQar4mVzwbx0PKzDmLYqnuaNcnRVxDVcv/j571l6oZUJL/ry+HYir+fbnvkPGwDBbwRpp8BlyJ6JWtdVvX2Fe81UTXB9NMFAHqLiOsmV5TVOAeGhlicfbv+OqGLb+aeulWSuiENUPQ51YGZdaEdOZYvg3y+zWx62QUORxbF2mqK8CpPyDqT7owDjjtgHyVnjnuPR5YG+i/3ruAGRpB678UNz1bghDTSMgyXf+9ylqHEWg=
  on:
    tags: true
    repo: shankarpandala/lazypredict